### PR TITLE
join: loosen cleanliness requirements for SecureJoin root

### LINKED ISSUE #46: [regression] hardening against bad root paths in 0.4.0 is too agressive
Requiring `filepath.Clean` paths means that root values with trailing `/`s will also error out. It might make more sense for us to just look for `..` components.

### PR DESCRIPTION
**Pull request by cyphar**
It turns out that some users do provide unclean paths like "foo/bar/"
and as a result the new behaviour in commit https://github.com/cyphar/filepath-securejoin/commit/bc750ad62e1e91382c72e623ced46099258aa887 ("join: return
an error if root is unclean path") was far too aggressive and lead to
regressions.

The more gentle solution is to only error out if the path contains a
".." component (which is the only component type we are really worried
about here because it's the only one that can turn a safe
root-joined-path into an unsafe one due to how symlinks are resolved on
Linux).

Fixes: bc750ad62e1e ("join: return an error if root is unclean path")
Fixes #46
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>

### CODE REVIEW

**Comment by cyphar** [comment]
@kolyshkin WDYT?

File: join.go [hunk 1]
```diff
@@ -24,9 +24,22 @@ func IsNotExist(err error) bool {
...
+// errUnsafeRoot is returned if the user provides SecureJoinVFS with a path
+// that contains ".." components.
+var errUnsafeRoot = errors.New("root path provided to SecureJoin contains '..' components")
+
+// hasDotDot checks if the path contains ".." components in a platform-agnostic
+// way.
+func hasDotDot(path string) bool {
+	if v := filepath.VolumeName(path); v != "" {
+		path = path[len(v):]
+	}
```
Comment (kolyshkin) [inline join.go:36]: Can be simplified to
```go
        path = path[len(VolumeName(path)):]
```

The whole thing will probably be optimized out by the compiler on Linux since VolumeName always returns "" there. Or maybe I am being overly optimistic wrt Go compiler :)

File: join_windows_test.go [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+func TestHasDotDot_WindowsVolumes(t *testing.T) {
+	for _, test := range []struct {
+		testName, path string
+		expected       bool
+	}{
+		{"plain-dotdot", `C:..`, true},            // apparently legal
+		{"relative-dotdot", `C:..\foo\bar`, true}, // apparently legal
+		{"trailing-dotdot", `D:\foo\bar\..`, true},
+		{"leading-dotdot", `F:\..\foo\bar`, true},
+		{"middle-dotdot", `F:\foo\..\bar`, true},
```
Comment (kolyshkin) [inline join_windows_test.go:24]: In Windows, there are many other ways to have a volume name. I remember `\\share\path\to\file`, but there's more; you can check e.g.  https://github.com/golang/go/blob/f6d17c540024418ca8a92371931b1b4fb076d2b6/src/path/filepath/path_test.go#L1553-L1614, or https://github.com/golang/go/blob/f6d17c540024418ca8a92371931b1b4fb076d2b6/src/internal/filepathlite/path_windows.go#L198-L250, or links provided in there).

Not sure how much of that you want to duplicate here; after all, we're not testing filepath.VolumeName.

**Review by kolyshkin — APPROVED** [review]
Left some notes but LGTM

File: join_windows_test.go (hunk 2 above)
Comment (cyphar) [reply join_windows_test.go:24]: My main worry was the `C:..\foo` case, which seems like it should be valid but the [only documentation I could find](https://learn.microsoft.com/en-us/dotnet/standard/io/file-path-formats) felt somewhat suspect (what does "current directory in the `C:` drive" in the  `C:foo\bar` case even mean -- does Windows have separate cwds for each process on each drive?).

I can add a few more cases though.

File: join.go (hunk 1 above)
Comment (cyphar) [reply join.go:36]: We do the same thing later for `remainingPath`, I'll combine them into one function.

Based on some [quick godbolt tests](https://godbolt.org/z/9e6fqEenf), the Go compiler is smart enough to make it a no-op but if you put it into a function the function is still included even though it's not used (though I guess the linker might get rid of it so looking at godbolt might not show that?).

File: join_windows_test.go (hunk 2 above)
Comment (cyphar) [reply join_windows_test.go:25]: Huh, it turns out that Go's `\\.\C:..` handling is not what you would naively expect. Let me check on a windows machine if this is a Go stdlib bug or not (it is possible that `C:..\foo` is invalid anyway).

Comment (cyphar) [reply join_windows_test.go:25]: Ah okay, I missed this:

> DOS device paths are fully qualified by definition and cannot begin with a relative directory segment (. or ..). Current directories never enter into their usage.

I'll adapt the failing tests...
